version: '3.8'

services:
  lethe-cfd:
    build:
      context: https://github.com/Pika-Zhihao/4.lethe-cfd-case-air-particles.git#main
      dockerfile: Dockerfile
    container_name: lethe-cfd
    ports:
      - "8888:8888"  # 如果你使用 Jupyter 或其他服务
    volumes:
      - /home/youruser/data:/lethe/data  # 修改为实际路径
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LETHE_USE_GPU=1
    working_dir: /lethe/build
    command: ["./lethe_solver", "/lethe/data/simulation.prm"]
    restart: unless-stopped
