version: '3.8'

services:
  lethe-cfd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lethe-cfd
    ports:
      - "8888:8888"
    volumes:
      - /home/youruser/data:/lethe/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
