version: '3.8'

services:
  lethe-cfd:
    image: pikazhihao/lethe-cfd:latest
    container_name: lethe_solver
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    working_dir: /lethe/build
    command: ["./lethe_solver", "/app/config/simulation.prm"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
