version: '3.8'

services:
  lethe-cfd:
    build:
      context: https://github.com/Pika-Zhihao/lethe-cfd-stack.git#main
      dockerfile: Dockerfile
    container_name: lethe-cfd
    ports:
      - "8888:8888"
    volumes:
      - /home/youruser/data:/lethe/data
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LETHE_USE_GPU=1
    working_dir: /lethe/build
    command: ["./lethe_solver", "/lethe/data/simulation.prm"]
    restart: unless-stopped
