version: '3.8'

services:
  lethe-cfd:
    build:
      context: https://github.com/Pika-Zhihao/lethe-cfd-stack.git#main
      dockerfile: Dockerfile
    container_name: lethe-cfd
    ports:
      - "8888:8888"  # 如果你使用 Jupyter 或其他服务
    volumes:
      - /home/youruser/data:/lethe/data  # 修改为实际路径
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped

